<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>City of Bloomington Utilities</title>
<link rel="stylesheet" href="<?= BASE_URL; ?>/css/global-<?= VERSION; ?>.css">
<link rel="stylesheet" href="<?= BASE_URL; ?>/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?= BASE_URL; ?>/vendor/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="<?= BASE_URL; ?>/vendor/jquery/ui/jquery-ui.min.css">
<script src="<?= BASE_URL; ?>/vendor/jquery/jquery-1.11.3.min.js"></script>
<script src="<?= BASE_URL; ?>/vendor/jquery/ui/jquery-ui.min.js"></script>
<script src="<?= BASE_URL; ?>/vendor/jquery-mask/jquery-mask.js"></script>
<script src="<?= BASE_URL; ?>/vendor/bootstrap/js/bootstrap.min.js"></script>
