<?php
/**
 * @copyright 2016 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 */
?>
<div class="contact-info" style="font-size:14px; margin:5px; padding:5px; border:1px solid #315DA6; border-radius:25px; padding:10px; margin-bottom:25px;">
    <span style="font-weight:bold; font-size:16px; padding:5px;">
        <center>Customer Service Office Contact Information</center>
    </span>
    <br />
    <table class="table">
        <tr>
            <td>Operating Hours</td><td>8:00 am to 5:00 pm M-F</td>
        </tr>
        <tr>
            <td>Address</td><td>600 E Miller Dr <br />Bloomington IN 47401</td>
        </tr>
        <tr>
            <td>Phone Number</td><td>(812) 349-3930</td>
        </tr>
        <tr>
            <td>Email Address</td><td><a href="mailto:utilities.cs@bloomington.in.gov">utilities.cs@bloomington.in.gov</td>
        </tr>
    </table>
</div>
